### ISSUE TITLE
What version of Ionic is this based upon?

### ISSUE THREAD

**Issue by skirunman** [reactionic/reactionic#1]
This is awesome, thanks for sharing.

Was wondering what version of Ionic you built this from, 1.2.4 or the 2.0.0 beta or did you fork the old Meteoric code? Would be awesome if it was based on the latest Ionic 2 release that is based on Angular 2 as this would be closer to React in concept and one could use the latest CSS and icons from the Ionic 2 release, which has added a ton of new features.

Here are the Ionic 2 list of components: http://ionicframework.com/docs/v2/components/#overview

**Comment by pors** [comment]
It is based on 1.2.4. I thought about using Ionic 2 when I started, but it wasn't ready then. I'm using this library for an app we are developing and I couldn't live without some of the features.

This was a couple of months ago, so maybe things are in a better state now with v2.

**Comment by pors** [comment]
Closing this, see #2 for follow up action
