### ISSUE TITLE
Does it make sense to upgrade to use `extends React.Component` from `React.createClass`

### ISSUE THREAD

**Issue by skirunman** [reactionic/reactionic#18]
I'd like to suggest a future upgrade to full ES6 and to `class foo extends React.Component` from `var foo = React.createClass` at some time in the future.

"Facebook does suggest the future removal of React.createClass completely in favour of ES6 classes. For now, use what makes sense, they’re both just syntax with different semantics that do the same thing - they’re both classes!"
https://toddmotto.com/react-create-class-versus-component/

**Comment by pors** [comment]
The React tutorial still uses `React.createClass`: https://facebook.github.io/react/docs/tutorial.html

I have a preference for `React.createClass`. The `extends` style looks too much like OOP, but Javascript isn't OOP. But that's just me :)

**Comment by skirunman** [comment]
I think the trend is definitely to embrace higher order components and the `extends React.Component` style, especially with ES6. For instance, the new [Meteor React Tutorial](http://1.3-tutorial.meteorapp.com/tutorial/1/react) uses this pattern and[ Kadira's Mantra](https://github.com/kadirahq/mantra/issues/17) also uses it. 

With that said, I think it is fine to continue to use `React.createClass` especially for this type of UI package, and of course, it is your code base so you obviously get to pick the style. 

Here is[ another take](http://jamesknelson.com/should-i-use-react-createclass-es6-classes-or-stateless-functional-components/) on the issue. 

I'll close this out for now.

**Comment by pors** [comment]
I think that last article is about something else?

Anyway, it indeed seems the `class extends` style is on the rise. As soon as Facebook starts recommending it we can fix it as well. But for now I want to focus on completing all functionality of Meteoric :)
