### ISSUE TITLE
Some native issue and suggest change meteoric to meteoric124 fork for prevent buggy version

### ISSUE THREAD

**Issue by cyclops24** [reactionic/reactionic#25]
Hi @pors ,

First thanks for extending ionic community by your new born project but I think if you based this project on [meteoric124](https://github.com/meteoric124/meteoric) it's more better because I check your project and it has so many native or UI bugs (bugs on real android device) because these bugs not solved on [main meteoric repository from Nick Wientge](https://github.com/meteoric/meteor-ionic) but many of them fixed in [meteoric124 fork from Joey Andres](https://github.com/meteoric124/meteoric) (for example [these bugs](https://github.com/meteoric124/meteoric/issues?utf8=%E2%9C%93&q=label%3Anative+) still exist on you project but fixed on meteoric124 fork some month ago) and also many complex feature like ion-infinite-scroll, ion-delete-button, ion-reorder-button and more done there.

Also many page load improvement and analysis like [this](https://github.com/meteoric124/meteoric/issues/42) and [this](https://github.com/meteoric124/meteoric/issues/53) by remove unnecessary ionIcon and deprecate that happened there.

I suggest you to communicate with @JoeyAndres and share experience between yourselves.
All of us have a same enemy (angular :smile: ) and same problem or task because both team try to port angular based ionic to non-angular. [Meteoric124](https://github.com/meteoric124/meteoric) use blaze and meteor based approach for solve problems but [React-Ionic](https://github.com/pors/reactionic) use react for solve them.

**Comment by pors** [comment]
Thanks. I am aware of meteoric124, and I will certainly address some of the bugs that have been fixed there. My first goal is to have all Meteoric functionality ported to React as fast as possible. There are many apps out there using Meteoric, and working fine with that.

That said, it is always a good idea to make it better and fix bugs, so when I have ported all functionality we can focus on how to make it better.

Did you guys look into Ionic 2 as well? I was thinking that as the next step.

cc @JoeyAndres

**Comment by pors** [comment]
Closing this for now, will revisit when it is more clear how we will proceed after main functionality has been implemented.

**Comment by cyclops24** [comment]
@pors I think Ionic 2 is a bit different and more clear. @JoeyAndres now a little busy and I think his know more about this.

@pors now I think [this issues](https://github.com/meteoric124/meteoric/issues?utf8=%E2%9C%93&q=label%3Anative+) is more important than Ionic 2 because bug on device equal app failure and all of the functionality lost their usage.

**Comment by pors** [comment]
Thanks, I'll have a look at these issues for sure!

**Comment by pors** [comment]
BTW can you reproduce these bugs with reactionic? The spinners work fine for me on Android e.g.

**Comment by cyclops24** [comment]
@pors Some of these bugs appear on older android versions (for example v4.2.1 that haven't good support for CSS3 animation) you can check on emulators (for example browse reactionic demo page by built-in web browser in emulator like [genymotion](https://www.genymotion.com/) or on older device)
I also try to reproduce and post one by one as new issue soon.

Thanks for your attention.
