### ISSUE TITLE
Upgrade to react 15

### ISSUE THREAD

**Issue by primeminister** [reactionic/reactionic#28]
Would be nice if react 15 is also supported.
Thanks!

**Comment by pors** [comment]
This includes an upgrade to react router v2. @cannoneyed is working on that

**Comment by primeminister** [comment]
@pors & @cannoneyed I see in helper animate.js some context.location that could be the problem. Part of the react-addons-css-transition-group class. No idea how to solve that

**Comment by primeminister** [comment]
Upgrading to React 15 does work, except the deprecation warning of router v2. No harm in there, but would be nice to have it fixed

**Comment by gerwinbrunner** [comment]
What's the state? Currently v0.2.0 seems to have a dependency to react-dom@0.14.8

**Comment by pors** [comment]
We haven't merged the PR yet because it causes some issues with React router. Shouldn't take long though

**Comment by gerwinbrunner** [comment]
Is there an ETA?

**Comment by primeminister** [comment]
Hi @gerwinbrunner , No ETA yet, if you want to speed up, you can help with the Router warnings. I will push my branch today, so you can check fork it.

**Comment by johnslemmer** [comment]
@primeminister I have been working on making this upgrade locally.  I'm really new to github (read I don't know what I'm doing or how to have my changes integrated in).  But I have made some changes in my fork to get this working.  take a look at my profile.

**Comment by pors** [comment]
@johnslemmer can you click on the green [New pull request] button here: https://github.com/johnslemmer/reactionic and here https://github.com/johnslemmer/reactionic-kitchensink ?

It is a bit easier for us to evaluate and see all diffs at once.

PS I think @primeminister also fixed this, but that doesn't matter, it's good to learn from everyone's code I think.

**Comment by primeminister** [comment]
Merged into master with PR #32 so closing this issue

**Comment by pors** [comment]
@johnslemmer are you on Twitter? Would like to mention you in a tweet about the update

**Comment by johnslemmer** [comment]
Yep, @johnslemmer

thanks
