### ISSUE TITLE
Update guide to reflect react-router v2 changes

### ISSUE THREAD

**Issue by pors** [reactionic/reactionic#34]
Some context definitions a needed in any app at the top level. Needs to be documented.

**Comment by johnslemmer** [comment]
@pors is this the expectation for passing react-router location around?  Because I'm still getting the following in 0.3.0. 

> ing: [react-router] `context.location` is deprecated, please use a route component's `props.location` instead. http://tiny.cc/router-accessinglocation

I noticed that we removed automatically adding location to the child context in IonBody and was wondering what we the plan was with that.

**Comment by pors** [comment]
@johnslemmer we added the childcontext for location to app.jsx (in the kitchen sink demo) as that is the top level route component.

But you are right, it might be better to put it in IonBody, and add to the guide that you need to pass props from your top level component to IonBody. At least the this.props.location prop i.e.

What do you think?

**Comment by johnslemmer** [comment]
@pors I could see the argument go either way.  To me it seems more elegant
to have the reactionic package set up the context types that it knows it is
going to need.  Passing props to IonBody feels pretty normal, and something
you would expect to do anyway.  Thats my two sense.

My preference was done in this commit but then got changed later.
https://github.com/reactionic/reactionic/commit/11e17e04fd1b920aa8cc2ac2c109ed57b1b2b8a2

**Comment by pors** [comment]
@johnslemmer yeah that's my mistake, I thought it had to go to the top router component, but it's much better if we keep it inside reactionic and pass props to IonBody.

I'll fix and update the guide as well. Thx!
