### ISSUE TITLE
ionPopup never clears this.state.inputValue

### ISSUE THREAD

**Issue by johnslemmer** [reactionic/reactionic#43]
So, even if you tap OK on a prompt popup the next time that the popup comes up it will still have the previous input value.

@pors I would just fix this, but I wanted to have a discussion first about how to appropriately accomplish this.  Are all users going to want this `this.state.inputValue` cleared on OK?  How about on cancel?  Or do we want to make it customizable and somehow allow the `onOK` and `onCancel` handlers have access to clearing `this.state.inputValue`?  If that is the case what is best way to allow this to happen?

Or should I just not use the built in `type: 'prompt'` and write a more explicit popup object to pass to `this.context.ionUpdatePopup` with a specific `template` that allows me to control what I want more?

**Comment by pors** [comment]
I think that the only case where we don't want to clear the input is if there is some error checking done and an error is triggered. But for a password field that doesn't really make sense.

Are you using it for a password or for a normal input field?

**Comment by johnslemmer** [comment]
A normal input field.

**Comment by pors** [comment]
In that case, we could maybe add another `prompt` type for normal text input, and add some error-checking callback? And if that returns 'no error' we reset the value.

**Comment by pors** [comment]
@johnslemmer would you like me to elaborate on this?

**Comment by johnslemmer** [comment]
Sorry, I didn't get back to you on this.  I actually went ahead and made my own template.  It just seemed easier.  Something like this worked out well for me:

```
    this.context.ionUpdatePopup({
      title: 'Save some text',
      template: <input
        type="text"
        placeholder="Some text to save..."
        onChange={this.handleTextChange}
      />,
      buttons: [{
        text: 'Cancel',
        type: 'button-assertive',
        onTap: this.cancelSave,
      }, {
        text: 'Add',
        type: 'button-balanced',
        onTap: this.handleSave,
      }],
    });

```

I would say that the popup is flexible enough to do what you want with that we don't need to add other specific types to reactionic itself.

**Comment by pors** [comment]
Ah great! Will close this one then.
