### ISSUE TITLE
Reactionic iOS index page slip

### ISSUE THREAD

**Issue by tommy0311** [reactionic/reactionic#44]
I observed index page will slip in iOS when index page is not list page.
The issue also can be reproduced in Kitchen sink demo.

![output_oh9dy4](https://cloud.githubusercontent.com/assets/12669644/15266836/8cf12e96-19e3-11e6-804c-99dd4918f315.gif)

**Comment by pors** [comment]
@tommy0311 I'm not sure what you mean with "when index page is not list page". Can you please explain?

**Comment by tommy0311** [comment]
@pors  In Kitchen sink demo, remove IonList from index.jsx. 
You can find index page slip in iOS

```
--- a/app/client/imports/components/index.jsx
+++ b/app/client/imports/components/index.jsx
@@ -26,9 +26,6 @@ var Index = React.createClass({
     return (
       <IonContent customClasses=""
                   {...this.props}>
-      <IonList>
-        {items}
-      </IonList>
       </IonContent>
     );
   }
```

**Comment by pors** [comment]
@tommy0311 hmm yes, that is a serious issue. Thanks for reporting. Will have a look at it soon. If you know a solution yourself, please fork and create a Pull Request (or post some comments here).

**Comment by pors** [comment]
I can reproduce it, also if IonList is in place. If you hold the header bar you can wiggle the whole view up and down.
Looking into a solution now

**Comment by pors** [comment]
@tommy0311 can you confirm that reactionic@1.1.2 fixes this issue? If not, please reopen.

**Comment by tommy0311** [comment]
@pors 
The 1.1.2 patch is work for Kitchen sink demo.
But my project still has very tiny whole-screen wiggling, the wigging was bigger.
I am going to figure out how to reproduce it in Kitchen sink demo.
If I find something, I will reopen this issue.
Thanks for your help.
