### ISSUE TITLE
IonSideMenu: would be nice to have the possibility to set the width of the side menu

### ISSUE THREAD

**Issue by RobDong** [reactionic/reactionic#46]
Like the angular version 
[http://ionicframework.com/docs/api/directive/ionSideMenu/]

```
<IonSideMenu width={myWidth}>
</IonSideMenu>
```

**Comment by pors** [comment]
@RobDong seems useful. We'll have a look at it. If you can create a simple solution yourself, please fork and create a Pull request.

**Comment by johnslemmer** [comment]
@RobDong I think you can.  reactionic uses [snap.js](https://github.com/jakiestfu/Snap.js/) internally to accomplish the side menus.  It has settings for `minPosition` and `maxPosition` that might be what you are looking for.  You just have to render the `IonSideMenuContainer` with the correct options.  Something like the following:

```
      <IonSideMenuContainer
        settings={{
          maxPosition: 400,
        }}
        {...this.props}
      >

```

Let us know if that get you what you need.

**Comment by RobDong** [comment]
@johnslemmer Yes thank you :). 
This is what I came up with for having a full screen sidebar :

```
let windowWidth = window.innerWidth;
this.context.ionSnapper.settings({minPosition: '-' + windowWidth});
this.context.ionSnapper.settings({maxPosition: windowWidth});
```

**Comment by pors** [comment]
Resolved, so closing
