### ISSUE TITLE
Right side menu will not disable

### ISSUE THREAD

**Issue by Streemo** [reactionic/reactionic#55]
```
//brevity
<IonSideMenus>
  <IonSideMenu side="left"></IonSideMenu>
</IonSideMenus>
<IonSideMenuContent/>
```

I am not including the right side menu, but I can still drag the main view content from the right, revealing an empty screen. Anyone else got that problem?

**Comment by RobDong** [comment]
I solve it with this : 
this.context.ionSnapper.settings({ disable: 'right'  });

**Comment by Streemo** [comment]
Isn't it not safe to be using context, a this is a very experimental feature? Is there another way to access the ionSnapper? Thanks.

**Comment by Streemo** [comment]
@RobDong I've figured out the context thing, it's a bit different with es6.

Do you know where to call `this.context.ionSnapper.settings`? In the render() method of the Layout, the ionSnapper is still `null`...

**Comment by Streemo** [comment]
Thanks @RobDong for mentioning `{disable: 'right'}`.

Apparently one must pass a `{disable: "right"}` into the props for the `<IonSideMenuContainer>`. I have no idea why something as necessary as this is not in the docs.

**Comment by pors** [comment]
@Streemo feel free to add it to the guide!

**Comment by johnslemmer** [comment]
Actually, I have been meaning to update the doc for the side menu as I had
made some changes there

**Comment by johnslemmer** [comment]
Ok, I have updated the guide.
