### ISSUE TITLE
How to Structure your App

### ISSUE THREAD

**Issue by Streemo** [reactionic/reactionic#56]
The structure below is what I landed on after playing around. It's not entirely clear where to put your reactive data source (Meteor users). 

If your app right now is `x`, think of this package as wrapping your app into `x' = reactionic(x)`. All of your reactivity should go under the `IonBody` coming from this package.

```
<Router history={browserHistory}>
 <Route path="/" component={IonApp /*contains IonBody in it*/}>
   <Route component={ReactiveMeteorContainerComponentLayout}>
    <IndexRoute component={MainPostsListView}/>
    <Route path="/posts/:id" component={PostsDetailView}/>
    <Route path="/messages" component={MessagesListView}/>
    <Route path="/messages/:id" component={MessagesDetailView}/>
    <Route path="*" component={Missing}/>
   </Route>
 </Route>
</Router>
```

If there's a better pattern, please share it here. Putting reactivity in the `IonApp` layer results in unnecessary lifecycle reruns.

**Comment by pors** [comment]
I have only been using the "old" ReactMeteorData mixin so far, but please have a look at the boilerplate here: https://github.com/johnslemmer/boilerplate-reactionic-meteor by @johnslemmer. I guess you best add a container for each component at the "lowest" point in your component hierarchy.

**Comment by Streemo** [comment]
That's a great link. Did you reference it in the docs? It should be!

Thanks for sharing 👍

**Comment by pors** [comment]
@Streemo We will do this as soon as the boilerplate is added to the reactionic organization. @johnslemmer is a member of the reactionic team.
