### ISSUE TITLE
Text inputs?

### ISSUE THREAD

**Issue by DarrylD** [reactionic/reactionic#57]
Do we plan to add any of them?

**Comment by ducdev** [comment]
Yes, I want a proper reactionic component for text inputs.

**Comment by DarrylD** [comment]
After digging around a bit, I'm not seeing the biggest usecase for them anymore. Was much easier to make my own stateless components with the ionic classes. Used other frameworks which controls the inputs, was a huge headache.

**Comment by pors** [comment]
@DarrylD yeah that was exactly my approach: all elements that can be created with standard React and Ionic CSS are not included in Reactionic.

**Comment by ducdev** [comment]
Hi guys, I don't know if this is right with you @DarrylD but this is exactly what I want:
`<IonItem input>
              <input ref="username" type="text" placeholder=" Username" />
            </IonItem>`

**Comment by DarrylD** [comment]
I have some components I made like this:

```
const ItemInput = ({val, handleSave, handleChange}) => {
    return (
        <div className="item">
            <label className="item-input-wrapper">
                <input
                    type="text"
                    value={val}
                    onKeyDown={handleSave}
                    onChange={handleChange}
                />
            </label>
        </div>
    )
}
```

**Comment by ducdev** [comment]
That's cool, in case people need a right component specified for Inputs. This should be merged with a PR.
Or we can easily wrap them by `<IonItem input></IonItem>`
