### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by DarrylD** [reactionic/reactionic#68]
Noticed `this.props.history` in the guide

```
var backButton = (
  <IonNavBackButton icon="ion-ios-arrow-back"
                    color=""
                    type="clear"
                    history={this.props.history}
                    customClasses="button-stage"
  />
);
```

What does that do? Not seeing any reference in the src.

**Comment by pors** [comment]
It provides the history object from here: https://github.com/reactionic/reactionic-kitchensink/blob/master/app/client/router.jsx#L97

This is needed for the back button to know what "back" means.

**Comment by pors** [comment]
Ah wait! That has been replaced by context now of course. Is indeed an error in the documentation. Thanks!
