### ISSUE TITLE
how do i upload this project to ionic.io?

### ISSUE THREAD

**Issue by sathyaincampus** [reactionic/reactionic#77]
how do i upload this project to ionic.io?
Usually with ionic, i do "ionic add platform android" and say "ionic upload". Can you tell me how I can upload the project created via your template to ionic and view that in the ionic-view app in android or ios?

**Comment by gabrielseco** [comment]
Probably, you'll need an ionic app to do it

We are using meteor, so you can install your app in android and ios simulators or generate an apk or an ipa and install it in your phone.

More information in the next link

https://www.meteor.com/tutorials/blaze/running-on-mobile
