### ISSUE TITLE
Cordova plugins

### ISSUE THREAD

**Issue by ACEEDesign** [reactionic/reactionic#78]
I know youre not supporting this anymore but is there a way to make cordova plugins, such as cordova-plugin-payment-iap and cordova-plugin-admobpro work?

**Comment by gabrielseco** [comment]
In theory it should be a meteor problem, if you're using reactionic-kitchensink example.

You only have to 

```
meteor add cordova:cordova-plugin-camera@1.2.0
```

You can read more here

https://guide.meteor.com/mobile.html#installing-plugins
